site_name: Schema Driven Configuration
nav:
  - Home: index.md
  - Installation: 
      - Overview: install/1_overview.md
      - Pre-Requisites: install/2_prereq.md
      - Kubernetes-collocated: install/3_k8s_collocated.md
      - Kubernetes-distributed: install/4_k8s_distributed.md
  - Getting Started: install/3_k8s_collocated.md
  - Concepts:
      - Schema-server: concepts/schema_server.md
      - Data-server: concepts/data_server.md
      - Cache: concepts/cache.md
      - Config-server: concepts/config_server.md
  - APIs:
    - apis:
      - Schema-server: apis/schema_server.md
      - Data-server: apis/data_server.md
      - Cache: apis/cache.md
    - crds:
      - Schema: crds/schema.md
      - DiscoveryRule: crds/discovery_rule.md
      - TargetConnectionProfile: crds/target_conn_profile.md
      - TargetSyncProfile: crds/target_sync_profile.md
      - Target: crds/target.md
      - Config: crds/config.md
  - Examples/Tutorials:
    - About: examples/0_about.md
    - K8s SR-Linux Collocated: examples/1_k8s_srl_collocated.md
    - K8s SROS Collocated: examples/2_k8s_sros_collocated.md
  - Development:
    - About: dev/about.md
  - Release Notes:
    - "0.0.1": rn/0.0.1.md
  - FAQ: faq/faq.md
  - Community: community/community.md

site_author: Wim Henderickx
site_description: >-
  Schema driven configuration is a system to configure devices through schema's (e.g. YANG) 
# repository
repo_name: iptecharch/docs
repo_url: https://github.com/iptecharch/docs
edit_uri: ""
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/flask
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: images/flask.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sdcio
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mgEKy6ax
    
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde