name: docs
on:
  workflow_dispatch:
  push:
    branches:
      - "docs-*"
    tags:
      - "v*"

env:
  MKDOCS_MATERIAL_VER: 9.1.4
  CONFIG_SERVER_VERSION: v0.0.4

jobs:
  publish:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'iptecharch/config-server'
          ref: '${CONFIG_SERVER_VERSION}'
          path: 'config-server-repo'
      - shell: bash
        run: |
          cd config-server-repo
          make manifests
      - run: docker run -v $(pwd):/docs --entrypoint ash squidfunk/mkdocs-material:${MKDOCS_MATERIAL_VER} -c 'git config --global --add safe.directory /docs; mkdocs gh-deploy --force --strict'